language: node_js
node_js:
  - "10"

cache: yarn
addons:
  chrome: stable
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

jobs:
  include:
    - stage: test
      install:
        - yarn install

      script:
        - yarn test:ci

      after_success:
        - yarn coveralls
